[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "infotaxis"
version = "0.1.0"
description = "Echolocation infotaxis search for single target"
readme = "README.md"
requires-python = ">=3.12"
license = {text = "Apache-2.0"}
authors = [
    {name = "Wu-Jung Lee", email = "leewujung@gmail.com"}
]
dependencies = [
    "matplotlib",
    "netcdf4",
    "numpy<2.4.0",
    "pandas",
    "seaborn",
    "scipy",
    "xarray",
]

[project.optional-dependencies]
dev = [
    "jupyter",
    "notebook",
    "ipykernel",
    "pytest",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["infotaxis*", "data_prep_plot*"]